---
- name: Create Promtail directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - "{{ promtail_config_dir }}"

- name: Deploy Promtail configuration
  template:
    src: promtail-config.yml.j2
    dest: "{{ promtail_config_dir }}/promtail-config.yml"
    mode: "0644"
  notify: restart stack

- name: Ensure log directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /var/log/app
    - /var/log/kong
  ignore_errors: yes
