---
- name: Create Kong directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - "{{ kong_config_dir }}"
    - "{{ kong_log_dir }}"

- name: Deploy Kong declarative config
  template:
    src: kong.yml.j2
    dest: "{{ kong_config_file }}"
    mode: "0644"
  notify: restart stack
