---
- name: Create Alertmanager config directory
  file:
    path: "{{ alertmanager_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create Alertmanager data directory
  file:
    path: "{{ alertmanager_data_dir }}"
    state: directory
    owner: "65534"
    group: "65534"
    mode: "0755"

- name: Deploy Alertmanager configuration
  template:
    src: alertmanager.yml.j2
    dest: "{{ alertmanager_config_dir }}/alertmanager.yml"
    mode: "0644"
  notify: restart stack
