---
- name: Create MySQL config directory
  file:
    path: "{{ app_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy MySQL init script
  template:
    src: init.sql.j2
    dest: "{{ app_config_dir }}/init.sql"
    mode: "0644"
  notify: restart stack

- name: Deploy MySQL exporter config
  template:
    src: mysql-exporter.cnf.j2
    dest: "{{ app_config_dir }}/.my.cnf"
    mode: "0600"
  notify: restart stack
