apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
type: Opaque
stringData:
  root-password: {{ .Values.secret.rootPassword | quote }}
  database: {{ .Values.secret.database | quote }}