app_config_dir: /opt/app
otel_dir: /opt/otel
app_log_dir: /var/log/app

app_frontend_port: 80
app_backend_port: 8080
app_db_port: 3306

spring_profile: "int"
app_port: 8080

mysql_database: "app-db"
mysql_user: "appuser"
mysql_password: "123456789"

# RDS connection URL — Spring Boot connects to AWS RDS instead of local MySQL
spring_datasource_url: "jdbc:mysql://{{ rds_endpoint }}:{{ rds_port }}/{{ mysql_database }}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"

otel_agent_version: "2.25.0"
otel_agent_jar: "/opt/otel/opentelemetry-javaagent.jar"
otel_service_name: "react-springboot-app"
otel_exporter_endpoint: "http://otel-collector:4317"

app_log_path: "/var/log/app/*.log"

